apiVersion: v1
kind: Service
metadata:
  name: {{ include "satis.fullname" . }}
  labels:
    {{- include "satis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.webhook.enabled }}
    - port: 8080
      targetPort: webhook
      protocol: TCP
      name: webhook
    {{- end }}
  selector:
    {{- include "satis.selectorLabels" . | nindent 4 }}
